###
POST http://localhost:1234/Produto/cadastrar
content-type: application/json

{  
    "nome": "testestes",
    "codigoBarras": "987",
    "preco": 100,
    "criadoEm": "2020-10-04"
}

###
GET http://localhost:1234/Produto/listar


